"""empty message

Revision ID: d1ffdd60c82f
Revises: f1fa29e77fab
Create Date: 2024-07-21 17:00:33.866735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd1ffdd60c82f'
down_revision: Union[str, None] = 'f1fa29e77fab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personmodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personmodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
