"""empty message

Revision ID: f1fa29e77fab
Revises: dcc015506602
Create Date: 2024-07-21 16:52:01.313480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f1fa29e77fab'
down_revision: Union[str, None] = 'dcc015506602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personmodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'usermodel', ['user_id'], ['id'])
        batch_op.drop_column('direccion')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personmodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
